services:
  - docker

dist: trusty
sudo: false
cache: bundler

git:
  depth: false

jobs:
  include:
    - stage: coditsu
      language: ruby
      rvm: 2.7.0
      before_install:
        - yes | gem update --system
      script: \curl -sSL https://api.coditsu.io/run/ci | bash

stages:
  - coditsu
