services:
  - docker

dist: trusty
sudo: false
cache: bundler

git:
  depth: false

jobs:
  include:
    - stage: coditsu
      language: ruby
      before_install:
        - gem update --system
        - gem install bundler
      before_script:
        - docker create -v /sources --name sources alpine:3.4 /bin/true
        - docker cp ./ sources:/sources
      script: >
        docker run
        -e CODITSU_API_KEY
        -e CODITSU_API_SECRET
        -e CODITSU_REPOSITORY_ID
        --volumes-from sources
        coditsu/build-runner:latest

stages:
  - coditsu
